service: C5-group-1-Capstone
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: ce5-grp1-capstone-deployment

functions:
  dispatcher:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
      

