service: CE5-grp1-email-sender

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  deploymentBucket:
    name: ce5-grp1-capstone-deployment
  environment:
    email_address: jmesthy@gmail.com

functions:
  sendEmail:
    handler: handler.lambda_handler
    events:
      - http:
          path: send-email
          method: post
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
            allowCredentials: false

#keep lambda package smaller
package:
  exclude:
    - node_modules/**
    - venv/**
